### ISSUE TITLE
error_route when routing

### ISSUE THREAD

**Issue by kerthcet** [theagentrouter/agent-router#579]
*Description*:
>Describe the issue.

This is how I yaml files look like:

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-ai-gateway-basic
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-ai-gateway-basic
  # namespace: envoy-ai-gateway-system
spec:
  gatewayClassName: envoy-ai-gateway-basic
  listeners:
    - name: http
      protocol: HTTP
      port: 80
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic
  # namespace: default
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: qwen2-0--5b
      backendRefs:
        - name: qwen2-0--5b
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: qwen2--5-0--5b
      backendRefs:
        - name: qwen2--5-0--5b
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: qwen2-0--5b
  # namespace: default
spec:
  schema:
    name: OpenAI
  backendRef:
    name: qwen2-0--5b-lb
    kind: Service
    port: 8080
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: qwen2--5-0--5b
  # namespace: default
spec:
  schema:
    name: OpenAI
  backendRef:
    name: qwen2--5-0--5b-lb
    kind: Service
    port: 8080
---
```

Basically I have two services `qwen2-0--5b-lb` and `qwen2--5-0--5b-lb`, However, when I query with:

```
 curl -H "Content-Type: application/json" \
    -d '{
        "model": "qwen2--5-0--5b-gguf",
        "messages": [
            {
                "role": "system",
                "content": "Hi."
            }
        ]
    }' \
    http://localhost:8080/v1/chat/completions
```

No response returned and I check the log, outputs:

```
{":authority":"localhost:8080","bytes_received":0,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:10080","downstream_remote_address":"127.0.0.1:57656","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"error_route","start_time":"2025-04-18T03:40:32.813Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"curl/8.4.0","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.244.1.33","x-request-id":"f5796270-0c5d-4fb9-b1d9-63476882ab80"}
```

If I port the svc directly, and query again, it works. Did I config wrong somewhere? 

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

Install via the recommended ways on website.

**Comment by mathetake** [comment]
I think thats because the route header matching rule is exact match by default (and that's the only type currently supported), not the prefix or regex.

**Comment by mathetake** [comment]
It looks you don't have `qwen2--5-0--5b-gguf` in the route.

**Comment by kerthcet** [comment]
Sorry, my mistake, it's:
```
 curl -H "Content-Type: application/json" \
    -d '{
        "model": "qwen2--5-0--5b",
        "messages": [
            {
                "role": "system",
                "content": "Hi."
            }
        ]
    }' \
    http://localhost:8080/v1/chat/completions
```

**Comment by mathetake** [comment]
Would it be possible for you to share the relevant extproc logs from extproc?

**Comment by kerthcet** [comment]
Thanks @mathetake , I solved this by reinstall the envoygateway, the env is destroyed so I can not provide any useful info right now, I'll close this. Once I met it again, I'll create another issue.

**Comment by gdagil** [comment]
I have this error too

envoy-default-envoy-ai-gateway-basic
```
[2025-05-12 09:17:49.390][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:23] Deprecated field: type envoy.config.route.v3.HeaderMatcher Using deprecated option 'envoy.config.route.v3.HeaderMatcher.exact_match' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
[2025-05-12 09:17:49.390][1][warning][misc] [source/common/protobuf/message_validator_impl.cc:23] Deprecated field: type envoy.config.route.v3.HeaderMatcher Using deprecated option 'envoy.config.route.v3.HeaderMatcher.exact_match' from file route_components.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.
2025-05-12T09:17:50.428Z	INFO	shutdown-manager	envoy/shutdown_manager.go:75	starting shutdown manager
{":authority":"localhost:60520","bytes_received":0,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:34084","duration":3,"method":"GET","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"ext_proc_error_gRPC_error_5","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:18:52.512Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36","x-envoy-origin-path":"/","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"e0111a25-7e60-4eb0-9636-cb000f86e1d3"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:58196","duration":2,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:18:59.520Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"6178118b-1a94-4bd2-8c22-c0f65eb8ae57"}
{":authority":"localhost:60520","bytes_received":0,"bytes_sent":131,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:58262","duration":1,"method":"GET","protocol":"HTTP/1.1","requested_server_name":null,"response_code":200,"response_code_details":"","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:19:02.953Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/models","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"6d75311b-a14a-43f3-98c1-f00e17a97da9"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:38642","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:19:21.042Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"a920e5c7-9837-4143-8f83-ea132261124e"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:48938","duration":2,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:33.670Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"b89dbf65-77a2-419d-8601-fa29f3c49f6d"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:48948","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:34.339Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"7d5de087-32ad-44c3-bbd9-99e2c0f3ffac"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:48970","duration":2,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:34.722Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"2bab49db-6280-45d0-b858-1622bff956b5"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:48986","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:35.083Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"cc455a6e-650c-423e-accc-ea8826a43d7d"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:48992","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:35.419Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"18f9e370-4a33-4e4a-a198-352e075c52ef"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:49006","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:35.939Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"181b7a50-dd6d-47db-8146-86ffa14a0831"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:49026","duration":1,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:36.713Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"0bd65ee6-6a0f-43e9-bc42-d94b5b570aee"}
{":authority":"localhost:60520","bytes_received":86,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:49038","duration":2,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:37.443Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"2bcb01dc-8da1-46f1-8c00-118b6fb0ed9e"}
{":authority":"localhost:60520","bytes_received":0,"bytes_sent":131,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:58788","duration":1,"method":"GET","protocol":"HTTP/1.1","requested_server_name":null,"response_code":200,"response_code_details":"","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:24:59.862Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/models","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"6863856c-51a2-4922-996b-4ca873f26736"}
{":authority":"localhost:60520","bytes_received":0,"bytes_sent":131,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:58792","duration":1,"method":"GET","protocol":"HTTP/1.1","requested_server_name":null,"response_code":200,"response_code_details":"","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:25:00.473Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/models","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"ab6d9c3b-5a00-4a02-a516-bf8d3830dc10"}
{":authority":"localhost:60520","bytes_received":0,"bytes_sent":131,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:58804","duration":1,"method":"GET","protocol":"HTTP/1.1","requested_server_name":null,"response_code":200,"response_code_details":"","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:25:00.922Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/models","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"070c95e1-26cd-465c-b7a4-d92806dde6af"}
{":authority":"localhost:60520","bytes_received":0,"bytes_sent":131,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:8080","downstream_remote_address":"127.0.0.1:58818","duration":1,"method":"GET","protocol":"HTTP/1.1","requested_server_name":null,"response_code":200,"response_code_details":"","response_flags":"-","route_name":"httproute/default/envoy-ai-gateway-basic/rule/1/match/0/*","start_time":"2025-05-12T09:25:01.442Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"axios/1.6.8","x-envoy-origin-path":"/v1/models","x-envoy-upstream-service-time":null,"x-forwarded-for":"10.233.64.178","x-request-id":"70d18437-db55-4c1b-81f8-b3f0699f6f71"}
```

ai-eg-route-extproc-envoy-ai-gateway-basic
```
time=2025-05-12T09:24:36.715Z level=DEBUG msg="request body processed" request_id=0bd65ee6-6a0f-43e9-bc42-d94b5b570aee is_upstream_filter=false response="request_body:{response:{header_mutation:{set_headers:{header:{key:\"x-ai-eg-model\"  raw_value:\"some-cool-self-hosted-model\"}}  set_headers:{header:{}}  set_headers:{header:{key:\"x-ai-eg-original-path\"  raw_value:\"/v1/chat/completions\"}}}  clear_route_cache:true}}"
time=2025-05-12T09:24:37.444Z level=DEBUG msg="handling a new stream" config_uuid=75dccc3f-ccef-4cec-81a3-4f12d0898c23
time=2025-05-12T09:24:37.444Z level=DEBUG msg="request headers processing" request_id=2bcb01dc-8da1-46f1-8c00-118b6fb0ed9e is_upstream_filter=false request_headers.:authority=localhost:60520 request_headers.:path=/v1/chat/completions request_headers.:method=POST request_headers.:scheme=http request_headers.accept="application/json, text/plain, */*" request_headers.content-type=application/json request_headers.request-start-time=1747041877006 request_headers.user-agent=axios/1.6.8 request_headers.content-length=86 request_headers.accept-encoding="gzip, compress, deflate, br" request_headers.x-forwarded-for=10.233.64.178 request_headers.x-forwarded-proto=http request_headers.x-envoy-external-address=127.0.0.1 request_headers.x-request-id=2bcb01dc-8da1-46f1-8c00-118b6fb0ed9e
time=2025-05-12T09:24:37.444Z level=DEBUG msg="request headers processed" request_id=2bcb01dc-8da1-46f1-8c00-118b6fb0ed9e is_upstream_filter=false response=request_headers:{}
time=2025-05-12T09:24:37.445Z level=DEBUG msg="request body processing" request_id=2bcb01dc-8da1-46f1-8c00-118b6fb0ed9e is_upstream_filter=false request="request_body:{body:\"{\\\"model\\\":\\\"some-cool-self-hosted-model\\\",\\\"messages\\\":[{\\\"role\\\":\\\"system\\\",\\\"content\\\":\\\"Hi.\\\"}]}\"  end_of_stream:true}  metadata_context:{}"
time=2025-05-12T09:24:37.445Z level=DEBUG msg="request body processed" request_id=2bcb01dc-8da1-46f1-8c00-118b6fb0ed9e is_upstream_filter=false response="request_body:{response:{header_mutation:{set_headers:{header:{key:\"x-ai-eg-model\"  raw_value:\"some-cool-self-hosted-model\"}}  set_headers:{header:{}}  set_headers:{header:{key:\"x-ai-eg-original-path\"  raw_value:\"/v1/chat/completions\"}}}  clear_route_cache:true}}"
time=2025-05-12T09:24:59.862Z level=DEBUG msg="handling a new stream" config_uuid=75dccc3f-ccef-4cec-81a3-4f12d0898c23
time=2025-05-12T09:24:59.862Z level=DEBUG msg="request headers processing" request_id=6863856c-51a2-4922-996b-4ca873f26736 is_upstream_filter=false request_headers.:authority=localhost:60520 request_headers.:path=/v1/models request_headers.:method=GET request_headers.:scheme=http request_headers.accept="application/json, text/plain, */*" request_headers.content-type=application/json request_headers.request-start-time=1747041899604 request_headers.user-agent=axios/1.6.8 request_headers.accept-encoding="gzip, compress, deflate, br" request_headers.x-forwarded-for=10.233.64.178 request_headers.x-forwarded-proto=http request_headers.x-envoy-external-address=127.0.0.1 request_headers.x-request-id=6863856c-51a2-4922-996b-4ca873f26736
time=2025-05-12T09:24:59.863Z level=INFO msg="Serving list of declared models"
time=2025-05-12T09:24:59.863Z level=DEBUG msg="request headers processed" request_id=6863856c-51a2-4922-996b-4ca873f26736 is_upstream_filter=false response="immediate_response:{status:{code:OK}  headers:{set_headers:{header:{key:\"content-length\"  raw_value:\"131\"}}  set_headers:{header:{key:\"content-type\"  raw_value:\"application/json\"}}}  body:\"{\\\"data\\\":[{\\\"id\\\":\\\"some-cool-self-hosted-model\\\",\\\"created\\\":1747041899,\\\"object\\\":\\\"model\\\",\\\"owned_by\\\":\\\"Envoy AI Gateway\\\"}],\\\"object\\\":\\\"list\\\"}\"  grpc_status:{}}"
time=2025-05-12T09:25:00.474Z level=DEBUG msg="handling a new stream" config_uuid=75dccc3f-ccef-4cec-81a3-4f12d0898c23
time=2025-05-12T09:25:00.474Z level=DEBUG msg="request headers processing" request_id=ab6d9c3b-5a00-4a02-a516-bf8d3830dc10 is_upstream_filter=false request_headers.:authority=localhost:60520 request_headers.:path=/v1/models request_headers.:method=GET request_headers.:scheme=http request_headers.accept="application/json, text/plain, */*" request_headers.content-type=application/json request_headers.request-start-time=1747041900210 request_headers.user-agent=axios/1.6.8 request_headers.accept-encoding="gzip, compress, deflate, br" request_headers.x-forwarded-for=10.233.64.178 request_headers.x-forwarded-proto=http request_headers.x-envoy-external-address=127.0.0.1 request_headers.x-request-id=ab6d9c3b-5a00-4a02-a516-bf8d3830dc10
time=2025-05-12T09:25:00.474Z level=INFO msg="Serving list of declared models"
time=2025-05-12T09:25:00.474Z level=DEBUG msg="request headers processed" request_id=ab6d9c3b-5a00-4a02-a516-bf8d3830dc10 is_upstream_filter=false response="immediate_response:{status:{code:OK}  headers:{set_headers:{header:{key:\"content-length\"  raw_value:\"131\"}}  set_headers:{header:{key:\"content-type\"  raw_value:\"application/json\"}}}  body:\"{\\\"data\\\":[{\\\"id\\\":\\\"some-cool-self-hosted-model\\\",\\\"created\\\":1747041900,\\\"object\\\":\\\"model\\\",\\\"owned_by\\\":\\\"Envoy AI Gateway\\\"}],\\\"object\\\":\\\"list\\\"}\"  grpc_status:{}}"
time=2025-05-12T09:25:00.923Z level=DEBUG msg="handling a new stream" config_uuid=75dccc3f-ccef-4cec-81a3-4f12d0898c23
time=2025-05-12T09:25:00.923Z level=DEBUG msg="request headers processing" request_id=070c95e1-26cd-465c-b7a4-d92806dde6af is_upstream_filter=false request_headers.:authority=localhost:60520 request_headers.:path=/v1/models request_headers.:method=GET request_headers.:scheme=http request_headers.accept="application/json, text/plain, */*" request_headers.content-type=application/json request_headers.request-start-time=1747041900664 request_headers.user-agent=axios/1.6.8 request_headers.accept-encoding="gzip, compress, deflate, br" request_headers.x-forwarded-for=10.233.64.178 request_headers.x-forwarded-proto=http request_headers.x-envoy-external-address=127.0.0.1 request_headers.x-request-id=070c95e1-26cd-465c-b7a4-d92806dde6af
time=2025-05-12T09:25:00.923Z level=INFO msg="Serving list of declared models"
time=2025-05-12T09:25:00.923Z level=DEBUG msg="request headers processed" request_id=070c95e1-26cd-465c-b7a4-d92806dde6af is_upstream_filter=false response="immediate_response:{status:{code:OK}  headers:{set_headers:{header:{key:\"content-length\"  raw_value:\"131\"}}  set_headers:{header:{key:\"content-type\"  raw_value:\"application/json\"}}}  body:\"{\\\"data\\\":[{\\\"id\\\":\\\"some-cool-self-hosted-model\\\",\\\"created\\\":1747041900,\\\"object\\\":\\\"model\\\",\\\"owned_by\\\":\\\"Envoy AI Gateway\\\"}],\\\"object\\\":\\\"list\\\"}\"  grpc_status:{}}"
time=2025-05-12T09:25:01.443Z level=DEBUG msg="handling a new stream" config_uuid=75dccc3f-ccef-4cec-81a3-4f12d0898c23
time=2025-05-12T09:25:01.443Z level=DEBUG msg="request headers processing" request_id=70d18437-db55-4c1b-81f8-b3f0699f6f71 is_upstream_filter=false request_headers.:authority=localhost:60520 request_headers.:path=/v1/models request_headers.:method=GET request_headers.:scheme=http request_headers.accept="application/json, text/plain, */*" request_headers.content-type=application/json request_headers.request-start-time=1747041901189 request_headers.user-agent=axios/1.6.8 request_headers.accept-encoding="gzip, compress, deflate, br" request_headers.x-forwarded-for=10.233.64.178 request_headers.x-forwarded-proto=http request_headers.x-envoy-external-address=127.0.0.1 request_headers.x-request-id=70d18437-db55-4c1b-81f8-b3f0699f6f71
time=2025-05-12T09:25:01.443Z level=INFO msg="Serving list of declared models"
time=2025-05-12T09:25:01.443Z level=DEBUG msg="request headers processed" request_id=70d18437-db55-4c1b-81f8-b3f0699f6f71 is_upstream_filter=false response="immediate_response:{status:{code:OK}  headers:{set_headers:{header:{key:\"content-length\"  raw_value:\"131\"}}  set_headers:{header:{key:\"content-type\"  raw_value:\"application/json\"}}}  body:\"{\\\"data\\\":[{\\\"id\\\":\\\"some-cool-self-hosted-model\\\",\\\"created\\\":1747041901,\\\"object\\\":\\\"model\\\",\\\"owned_by\\\":\\\"Envoy AI Gateway\\\"}],\\\"object\\\":\\\"list\\\"}\"  grpc_status:{}}"
```

My config from docs:
```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-ai-gateway-basic
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  gatewayClassName: envoy-ai-gateway-basic
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
      name: http
      port: 8080
      protocol: HTTP
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  rules:
    - backendRefs:
        - kind: AIServiceBackend
          name: envoy-ai-gateway-basic-testupstream
          weight: 1
      matches:
        - headers:
            - name: x-ai-eg-model
              type: Exact
              value: some-cool-self-hosted-model
  schema:
    name: OpenAI
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: envoy-ai-gateway-basic
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-basic-testupstream
  namespace: default
spec:
  backendRef:
    kind: Service
    name: envoy-ai-gateway-basic-testupstream
    namespace: default
    port: 8080
  schema:
    name: OpenAI
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ai-gateway-basic-testupstream
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-ai-gateway-basic-testupstream
  template:
    metadata:
      labels:
        app: envoy-ai-gateway-basic-testupstream
    spec:
      containers:
        - name: testupstream
          image: docker.io/envoyproxy/ai-gateway-testupstream:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: TESTUPSTREAM_ID
              value: test
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-ai-gateway-basic-testupstream
  namespace: default
spec:
  selector:
    app: envoy-ai-gateway-basic-testupstream
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
```
