### ISSUE TITLE
Allow users to add their custom external processor before/after the default one

### ISSUE THREAD

**Issue by neozhixuan** [theagentrouter/agent-router#590]
*Description*:
Currently, there is a default external processor to handle request/response transformation and token rate limiting. It is added into the gateway via the EnvoyExtensionPolicy which cannot be overridden. In the scenario where users want to add their own external processor before/after this external processor, they would need to copy the current external processor into a new EnvoyExtensionPolicy and override the existing policy.

It would be good to have a template/resource that can allow for this flexibility, because a custom external processor would be important for users with specific use cases to implement custom logic before a request is sent out / after a response is received.

**Comment by kerthcet** [comment]
I think we need a document about how to add custom external processors? cc @mathetake

**Comment by mathetake** [comment]
so currently EEP is attached at Gateway level, but if we change that to Route level (it's an implementation detail so we can do that), you can create your own EEP and attach it to the Gateway level, which effectively introduces "before" phases (which will be available in the upcoming latest EG v1.4). On the other hand, as you suggested, we can introduce some templating for full flexibility and better UX. But before investing cycles on it, could you share your exact use cases for each before and after custom processing? I would like to understand why people need, especially, after phase @neozhixuan

**Comment by kerthcet** [comment]
Sorry, I'm not a envoy expert, but doesn't we already support a list of external processors, for example:
```
spec:
  extProc:
  - backendRefs:
    - group: ""
      kind: Service
      name: ai-eg-route-extproc-default-envoy-ai-gateway
      namespace: default
      port: 1063
    metadata:
      writableNamespaces:
      - io.envoy.ai_gateway
    processingMode:
      allowModeOverride: true
      request:
        body: Buffered
      response:
        body: Buffered
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: default-envoy-ai-gateway
```

We can add several references under `spec.extProc`, which means support custom external processor.
 **Or** what you want here is the **Priority Strategy**, before/after specifically? If so, what's the default order for processor list, randomly?

Thanks.

**Comment by neozhixuan** [comment]
Thanks for getting back to me!

@mathetake To me, one use case for having a custom external processor after Envoy AI Gateway's external processor, would firstly be to validate that the model in the inference request is recognised by the Envoy AI Gateway's external processor and can be routed by the route filter (e.g. the default external processor would approve the request with a `msg="selected backend" backend=xxx schema="{Name:OpenAI Version:}"`). Secondly, our custom external processor can receive the necessary headers from the default external processor, like `x-user-id`, `x-request-id`, `x-ai-eg-model` and `x-ai-eg-selected-backend`, and do internal validations, or add specific headers for specific models. If LLM token count is passed to the custom external processor in the future, the custom external processor could use the LLM token count to do different rate limits for different models.

@kerthcet Yes, it is possible if we edit the existing EnvoyExtensionPolicy directly, as this resource cannot be overridden (e.g. if we want to have multiple external processors, we must define a separate EnvoyExtensionPolicy with the default external processor + our own external processors, and that policy must be recognised by the gateway in place of the existing one). Therefore I am trying to see if it is possible to make this more flexible and allow for external processors to process the request before/after the current one.

For example, this is how I hardcode the policy at the moment:
```yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyExtensionPolicy
metadata:
  name: custom-external-processors-policy
  namespace: xxx
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-ai-gateway
  extProc:
  - messageTimeout: 2000s
    backendRefs: 
    - group: ""
      kind: Service
      name: ai-eg-route-extproc-envoy-ai-gateway # default ext proc
      namespace: xxx
      port: 1063
    metadata:
      writableNamespaces:
      - io.envoy.ai_gateway
    processingMode:
      allowModeOverride: true
      request:
        body: Buffered
      response:
        body: Buffered
  - messageTimeout: 2000s
    backendRefs: 
    - name: grpc-ext-proc # custom ext proc
      kind: Service
      port: 9002
      namespace: xxx   
    processingMode:
      request: {}
      response: {}
```

Thanks all!
