### ISSUE TITLE
default AIGatewayRoute backend

### ISSUE THREAD

**Issue by codefromthecrypt** [theagentrouter/agent-router#612]
*Description*:

Right now, it appears that you need to set a custom header in order to route requests to a single backend (e.g. ollama).

e.g. `curl ... -H 'aigw-backend-selector: ollama'` will pass to ollama like this.
```
    - matches:
        - headers:
            - type: Exact
              name: aigw-backend-selector
              value: ollama
      backendRefs:
        - name: ollama
          namespace: default
```

Here's the full configuration I would like to simplify

<details>

```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aigw-run
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: aigw-run
spec:
  gatewayClassName: aigw-run
  listeners:
    - name: http
      protocol: HTTP
      port: 1975
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy-ai-gateway
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: aigw-run
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: aigw-run
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: aigw-backend-selector
              value: ollama
      backendRefs:
        - name: ollama
          namespace: default
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: ollama
spec:
  timeouts:
    request: 3m
  schema:
    name: OpenAI
  backendRef:
    name: ollama
    kind: Backend
    group: gateway.envoyproxy.io
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: ollama
spec:
  endpoints:
    - ip:
        address: 0.0.0.0
        port: 11434
```
</details>

However, as far as I know, you can't specify a default backend. This makes programmatic access not portable.

For example, here's how to add the headers with openai
```python
    client = openai.Client(default_headers={"aigw-backend-selector": "ollama"})
```

In summary, having a default route (backend, not just model) is important. Particularly, single backend configurations will find having to configure a header unnecessary toil. Even where possible, it adds work that isn't required in alternative platforms.

### Prior art

Here are similar configs in other products that accomplish this. Having something that can do the same in envoy ai-gateway seems a great way to allow folks to transition.

[archgw](https://github.com/katanemo/archgw):
```yaml
llm_providers:
  - name: qwen3:0.6b
    provider_interface: openai
    # This configuration is converted to Envoy and run inside Docker.
    endpoint: host.docker.internal:11434
    model: qwen3:0.6b
    default: true
```

[litellm](https://github.com/BerriAI/litellm):
```yaml
model_list:
  - model_name: "*"
    litellm_params:
      model: openai/*
      api_base: os.environ/OPENAI_BASE_URL
      api_key: os.environ/OPENAI_API_KEY
```

also, a couple proxies have even simpler config

[open-responses](https://github.com/masaic-ai-platform/open-responses): specifies a target `OPENAI_BASE_URL` which is the default egress
[llama-stack](https://github.com/meta-llama/llama-stack): has a distribution that bakes in ollama egress: llamastack/distribution-ollama

**Comment by mathetake** [comment]
i believe this is a reasonable request. The feature parity is important to compete with similar softwares as well as to provide a smooth migration path. I think one naive option to allow this is to add `default` flag to a rule

```diff
diff --git a/api/v1alpha1/api.go b/api/v1alpha1/api.go
index a24dddc..8fccef2 100644
--- a/api/v1alpha1/api.go
+++ b/api/v1alpha1/api.go
@@ -201,6 +201,13 @@ type AIGatewayRouteSpec struct {
 
 // AIGatewayRouteRule is a rule that defines the routing behavior of the AIGatewayRoute.
 type AIGatewayRouteRule struct {
+       // Default is a flag that indicates whether this rule is the default rule.
+       // When true, Matches will be ignored and this rule will be used as the default rule.
+       // Only AIGatewayRouteRule can exist in the AIGatewayRoute.
+       //
+       // Default is false.
+       Default bool `json:"default,omitempty"`
+
```

and the other way is to add "Path" matching to AIGatewayRouteRuleMatch like this

```diff
diff --git a/api/v1alpha1/api.go b/api/v1alpha1/api.go
index a24dddc..b9c7730 100644
--- a/api/v1alpha1/api.go
+++ b/api/v1alpha1/api.go
@@ -283,6 +283,9 @@ type AIGatewayRouteRuleMatch struct {
        // +kubebuilder:validation:MaxItems=16
        // +kubebuilder:validation:XValidation:rule="self.all(match, match.type != 'RegularExpression')", message="currently only exact match is supported"
        Headers []gwapiv1.HTTPHeaderMatch `json:"headers,omitempty"`
+       // Path specifies the HTTP request path matchers. See PathMatch in the Gateway API for the details:
+       // https://gateway-api.sigs.k8s.io/reference/spec/#httppathmatch
+       Path *string `json:"path,omitempty"`
 }
```

which matches the GWAPI and allows users to use "/" as default path vs this causes some conflicts with the concept of "Unified API" in this project that basically indicates the routing should be agnostic based on the path (and complicates the translation etc). I believe that's the reason why we haven't had Path based routing right now.

thoughts? @envoyproxy/ai-gateway-maintainers  @arkodg

**Comment by mathetake** [comment]
Now it's possible to define a default route/backend thanks to the refactoring #793.

Example config is in https://github.com/envoyproxy/ai-gateway/pull/842. More specifically, you can now define the wildcard matching on models 

```yaml
    # Fallback any other request to the OpenAI backend if no other rules match.
    - matches:
        - headers:
            - type: RegularExpression
              name: x-ai-eg-model
              value: .*
      backendRefs:
        - name: openai
          namespace: default
```
