### ISSUE TITLE
Upstream filter is not patched for envoy cluster going through proxy

### ISSUE THREAD

**Issue by yuzisun** [theagentrouter/agent-router#622]
*Description*:
With the new upstream filter change, it is relying on the load assignments to pass the metadata between the two filters. However for proxy case envoy cluster does not have load assignment and upstream filter is not patched, breaking the cloud traffic going through proxy, this setup works before the upstream filter change. 

*Repro steps*:
1.  Update envoy bootstrap config to add loopback listener and cluster a http proxy
```yaml
      static_resources:
        clusters:
          - name: external_proxy_cluster
            connect_timeout: 30s
            type: STRICT_DNS
            lb_policy: ROUND_ROBIN
            load_assignment:
              cluster_name: proxy_cluster
              endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: {{ .Values.proxy.url }}
                        port_value: {{ .Values.proxy.port }}
        listeners:
          - name: loopback_listener
            address:
              socket_address:
                address: 127.0.0.1
                port_value: {{ .Values.loopBackPort }}
            listener_filters:
            - name: tls_inspector
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.listener.tls_inspector.v3.TlsInspector
            filter_chains:
            - filters:
              - name: tcp
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.tcp_proxy.v3.TcpProxy
                  stat_prefix: tcpproxy
                  cluster: external_proxy_cluster
                  tunneling_config:
                    hostname: "%REQUESTED_SERVER_NAME%:443"
```
2. Setup AWS backend going through the http proxy
```yaml
kind: Backend
metadata:
  name: bedrock-us-east-1
  namespace: gateway
spec:
  endpoints:
  - ip:
      address: 127.0.0.1
      port: 10002
---
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: bedrock-us-east-1
  namespace: gateway
spec:
  targetRefs:
  - group: gateway.envoyproxy.io
    kind: Backend
    name: bedrock-us-east-1
  validation:
    caCertificateRefs:
    - group: ""
      kind: ConfigMap
      name: ca-bundle
    hostname: bedrock-runtime.us-east-1.amazonaws.com
```
3. Upstream filter is not patched because it is checking the load assignment, following is the rendered envoy config:
```
{
     "version_info": "4f5e58f2b0751b2cc9e207b671fcf4d9c9a479d5f692e1d20b928bb82318d4ba",
     "cluster": {
      "@type": "type.googleapis.com/envoy.config.cluster.v3.Cluster",
      "name": "httproute/gateway/ai/rule/4",
      "type": "EDS",
      "eds_cluster_config": {
       "eds_config": {
        "ads": {},
        "resource_api_version": "V3"
       },
       "service_name": "httproute/gateway/ai/rule/4"
      },
      "connect_timeout": "10s",
      "per_connection_buffer_limit_bytes": 32768,
      "lb_policy": "LEAST_REQUEST",
      "circuit_breakers": {
       "thresholds": [
        {
         "max_retries": 1024
        }
       ]
      },
      "dns_lookup_family": "V4_PREFERRED",
      "common_lb_config": {
       "locality_weighted_lb_config": {}
      },
      "ignore_health_on_host_removal": true,
      "transport_socket_matches": [
       {
        "name": "httproute/gateway/ai/rule/4/tls/0",
        "match": {
         "name": "httproute/gateway/ai/rule/4/tls/0"
        },
        "transport_socket": {
         "name": "envoy.transport_sockets.tls",
         "typed_config": {
          "@type": "type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext",
          "common_tls_context": {
           "combined_validation_context": {
            "default_validation_context": {
             "match_typed_subject_alt_names": [
              {
               "san_type": "DNS",
               "matcher": {
                "exact": "bedrock-runtime.us-east-1.amazonaws.com"
               }
              }
             ]
            },
            "validation_context_sds_secret_config": {
             "name": "bedrock-us-east-1/gateway-ca",
             "sds_config": {
              "ads": {},
              "resource_api_version": "V3"
             }
            }
           }
          },
          "sni": "bedrock-runtime.us-east-1.amazonaws.com"
         }
        }
       }
      ]
     },
     "last_updated": "2025-05-18T15:58:15.566Z"
    },
```

*Logs*:
```
2025-05-18T15:56:57Z	INFO	envoy-gateway-extension-server	LoadAssignment is nil	{"cluster_name": "httproute/gateway/ai/rule/4"}
2025-05-18T15:56:57Z	INFO	envoy-gateway-extension-server	LoadAssignment is nil	{"cluster_name": "httproute/gateway/ai/rule/5"}
2025-05-18T15:56:57Z	INFO	envoy-gateway-extension-server	LoadAssignment is nil	{"cluster_name": "httproute/gateway/ai/rule/6"}
```
