### ISSUE TITLE
Request override based on model + tenant in AIGatewayRoute

### ISSUE THREAD

**Issue by pksukumar** [theagentrouter/agent-router#695]
*Description*:
Currently we can override the request based on model parameter in request body.
```
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: envoy-ai-gateway-basic
  namespace: default
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: envoy-ai-gateway-basic
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: gpt-4.5-preview
      backendRefs:
```
But it would be better if we configure our own parameter here like model + tenant by passing tenant in the request body,

It would be good if we can able to configure AIGatewayRoute like below,
```
rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: gpt-4.5-preview
            - type: Exact
              name: x-ai-eg-tenant
              value: tenantA
```
Then we can hit a specific backend by specifying both model + tenant in the request body like below.

```
curl -H "Content-Type: application/json" \
  -d '{
    "model": "gpt-4o",
    "tenant": "tenantA",
    "messages": [
      {
        "role": "user",
        "content": "Hi."
      }
    ]
  }' \
  $GATEWAY_URL/v1/chat/completions
```

It would be essential to have this for our usecase because we have multiple teams running in our organisation which uses their own model endpoints.

One way is to create gateway endpoint for each team for now. But instead of it, the above solution seems better and it can scale across multiple teams with minimal changes.
