### ISSUE TITLE
[Question] `make precommit` has error.

### ISSUE THREAD

**Issue by yuluo-yx** [theagentrouter/agent-router#704]
*Description*:

My local os is Windows. In order to ensure the compatibility of make, I use the docker ubuntu container to run make precommit. But I encountered the following problems:

```
root@6a2360b6d1c2:/app# make codespell
spell => ./...
/bin/sh: line 1: /app/.bin/.venv/codespell@v2.3.0/bin/codespell: No such file or directory
make: *** [Makefile:70: codespell] Error 127
root@6a2360b6d1c2:/app#
```

As you can see, I mounted the project directory to the app directory of the container. I made sure I had installed the infrastructure required for make precommit and I start the container using docker compose as follows:

```yml
services:
  envoy-ai-gateway:
    container_name: envoy-ai-gw-base
    image: envoy-ai-gateway-base:V20250611
    volumes:
      - D:\open_sources\ai-gateway:/app
    command: tail -f /dev/null
```

Any guidance on this? thanks
