### ISSUE TITLE
Working docker+ollama (exclusively) example for CLI (aigw)

### ISSUE THREAD

**Issue by codefromthecrypt** [theagentrouter/agent-router#712]
*Description*:

I'd like to have a working docker example which can help workaround issues like #650 I've started on this, but there are a few kinks.

1. aigw should ideally have a `pull` command to get the envoy binary. This helps with a builder image as you can avoid having to keep re-pulling envoy.

2. we need an example of ollama (or similar anything from localhost) working not using IP address, rather fqdn hostname of host.docker.internal or similar

3. I'd love to be able to substitute and ENV var for the model, or even leave it out in the config yaml vs having to hard-code. A pass-through is a much better dev story and makes things not as difficult as other platforms.

4. 500 errors ideally could include some sort of reason why they bombed, or even better be coersed to an appropriate alternative, e.g. 503 if that was the reason

5. ideally, there is an example here in this repo which at least includes a tentative Dockerfile or even better a published image of the CLI. This would be simplified to not require extra headers, just solely support ollama or llama.cpp or vllm or whatever your local hosted inference plaform is, and no bedrock or other stuff. 

Here is the example I began, but it isn't working as I get 500s trying to access the server with openai. In docker, you can't see why there is a 500, but if you replace host.docker.internal with localhost and run directly, the error is better "no processor defined for path: /v1"

<details>

```
time=2025-06-16T10:54:04.956+08:00 level=INFO msg="Writing Envoy Gateway config" path=/var/folders/4s/__48jlq14dq3t6d4t5m5yrfh0000gn/T/envoy-gateway-config.yaml
time=2025-06-16T10:54:04.956+08:00 level=INFO msg="Creating Envoy Gateway resource file" path=/var/folders/4s/__48jlq14dq3t6d4t5m5yrfh0000gn/T/envoy-ai-gateway-resources/config.yaml
time=2025-06-16T10:54:04.956+08:00 level=INFO msg="Writing back non-target object into the output as-is" kind=GatewayClass name=aigw-run
time=2025-06-16T10:54:04.957+08:00 level=INFO msg="Writing back non-target object into the output as-is" kind=EnvoyProxy name=envoy-ai-gateway
time=2025-06-16T10:54:04.957+08:00 level=INFO msg="Writing back non-target object into the output as-is" kind=Backend name=ollama
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake creating" kind=AIServiceBackend name=openai
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake reconciling" kind=AIServiceBackend name=openai
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Reconciling AIServiceBackend" namespace=default name=openai
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake creating" kind=AIServiceBackend name=ollama
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake reconciling" kind=AIServiceBackend name=ollama
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Reconciling AIServiceBackend" namespace=default name=ollama
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake creating" kind=AIGatewayRoute name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake reconciling" kind=AIGatewayRoute name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Reconciling AIGatewayRoute" namespace=default name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="syncing AIGatewayRoute" namespace=default name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="creating HTTPRoute" namespace=default name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Gateway not found" namespace=default name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake creating" kind=Gateway name=aigw-run
time=2025-06-16T10:54:04.987+08:00 level=INFO msg="Fake reconciling" kind=Gateway name=aigw-run
time=2025-06-16T10:54:04.989+08:00 level=INFO msg="Running external process" config="{UUID:aigw-run MetadataNamespace:io.envoy.ai_gateway LLMRequestCosts:[] Schema:{Name:OpenAI Version:v1} ModelNameHeaderKey:x-ai-eg-model SelectedRouteHeaderKey:x-ai-eg-selected-route Rules:[{Name:aigw-run-rule-0 Headers:[{Type:<nil> Name:x-ai-eg-model Value:qwen3:0.6B}] Backends:[{Name:ollama.default ModelNameOverride: Schema:{Name:OpenAI Version:v1} Auth:<nil>}] ModelsOwnedBy:Envoy AI Gateway ModelsCreatedAt:0001-01-01 00:00:00 +0000 UTC}]}"
time=2025-06-16T10:54:04.990+08:00 level=INFO msg="starting external processor" version=dev address=unix:///var/folders/4s/__48jlq14dq3t6d4t5m5yrfh0000gn/T/uds.sock configPath=/var/folders/4s/__48jlq14dq3t6d4t5m5yrfh0000gn/T/extproc-config.yaml
time=2025-06-16T10:54:04.990+08:00 level=INFO msg="starting metrics server" address=:1064
time=2025-06-16T10:54:04.990+08:00 level=INFO msg="loading a new config" path=/var/folders/4s/__48jlq14dq3t6d4t5m5yrfh0000gn/T/extproc-config.yaml
time=2025-06-16T10:54:04.990+08:00 level=INFO msg="start watching the config file" path=/var/folders/4s/__48jlq14dq3t6d4t5m5yrfh0000gn/T/extproc-config.yaml interval=5s
time=2025-06-16T10:54:04.990+08:00 level=INFO msg="Starting health check HTTP server" addr=:1065
looking up the latest patch for Envoy version 1.33
1.33.2 is already downloaded
starting: /tmp/envoy-gateway/versions/1.33.2/bin/envoy with --admin-address-path /tmp/envoy-gateway/runs/1750042445379483000/admin-address.txt
[2025-06-16 10:54:05.441][17008986][warning][config] [source/server/options_impl_platform_default.cc:9] CPU number provided by HW thread count (instead of cpuset).
discovered admin address: 127.0.0.1:57450
time=2025-06-16T10:54:08.290+08:00 level=DEBUG msg="handling a new stream" config_uuid=aigw-run
time=2025-06-16T10:54:08.291+08:00 level=ERROR msg="cannot get processor" error="no processor defined for path: /v1"
{":authority":"localhost:1975","bytes_received":650,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"127.0.0.1:1975","downstream_remote_address":"127.0.0.1:57454","duration":2,"method":"POST","protocol":"HTTP/1.1","requested_server_name":null,"response_code":500,"response_code_details":"ext_proc_error_gRPC_error_5","response_flags":"-","route_name":"httproute/default/aigw-run/rule/1/match/0/*","start_time":"2025-06-16T02:54:08.289Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"curl/8.7.1","x-envoy-origin-path":"/v1","x-envoy-upstream-service-time":null,"x-forwarded-for":"192.168.0.107","x-request-id":"fd8e5324-0d10-45a6-94d0-4ffc9dd316a5"}
```

</details>

```Dockerfile
FROM golang:1.24 AS builder

RUN CGO_ENABLED=0 go install github.com/envoyproxy/ai-gateway/cmd/aigw@main

# TODO: pre-cache the envoy binary using aigw or worst case func-e to same directory

FROM gcr.io/distroless/static-debian11:nonroot

COPY --from=builder /go/bin/aigw /usr/bin/aigw
COPY ai-gateway.yaml .

# OpenAI API
EXPOSE 1975

# extproc and Prometheus metrics
EXPOSE 1064

USER nonroot:nonroot
ENTRYPOINT ["/usr/bin/aigw", "run"]
CMD ["ai-gateway.yaml", "--debug"]
```

ai-gateway.yaml
```yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: aigw-run
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: aigw-run
  namespace: default
spec:
  gatewayClassName: aigw-run
  listeners:
    - name: http
      protocol: HTTP
      port: 1975
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy-ai-gateway
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-ai-gateway
  namespace: default
spec:
  logging:
    level:
      default: error
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: aigw-run
  namespace: default
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: aigw-run
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: qwen3:0.6B
      backendRefs:
        - name: ollama
          namespace: default
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: ollama
  namespace: default
spec:
  timeouts:
    request: 3m
  schema:
    name: OpenAI
  backendRef:
    name: ollama
    kind: Backend
    group: gateway.envoyproxy.io
    namespace: default
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: ollama
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: host.docker.internal
        port: 11434
```

docker-compose.yaml
```
services:
  aigw:
    container_name: aigw
    build:
      context: .
    env_file:
      - env.local
    ports:
      - "1975:1975"
      - "1064:1064"
```

env.local
```bash
OPENAI_BASE_URL=http://localhost:1975/v1
OPENAI_API_KEY=unused
CHAT_MODEL=qwen3:0.6B
```

start command of ollama
```bash
OLLAMA_HOST=0.0.0.0 OLLAMA_CONTEXT_LENGTH=8192 ollama serve
```
