### ISSUE TITLE
invalid secret content will cause envoyproxy cannot start-up

### ISSUE THREAD

**Issue by Xunzhuo** [theagentrouter/agent-router#742]
*Description*:
>What issue is being seen? Describe what should be happening instead of
the bug, for example: Envoy should not crash, the expected value isn't
returned, etc.

![Image](https://github.com/user-attachments/assets/4d050abe-a100-4350-b504-0c7a7ac29e8b)

```
  Warning  FailedMount  19s (x7 over 51s)  kubelet            MountVolume.SetUp failed for volume "ai-gateway-envoy-ai-gateway-basic-default" : secret "envoy-ai-gateway-basic-default" not found
```

*Repro steps*:
> Include sample requests, environment, etc. All data and inputs
required to reproduce the bug.

```
apiVersion: v1
kind: Secret
metadata:
  name: envoy-ai-gateway-basic-aws-credentials
  namespace: default
type: Opaque
stringData:
  # Replace with your AWS credentials.
  apiKey: OPENAI_API_KEY  # Replace with your OpenAI API key.
```

*Logs*:
>Include the access logs and the Envoy logs.

```
2025-06-21T09:46:05Z    ERROR   Reconciler error        {"controller": "gateway", "controllerGroup": "gateway.networking.k8s.io", "controllerKind": "Gateway", "Gateway": {"name":"envoy-ai-gateway-basic","namespace":"default"}, "namespace": "default", "name": "envoy-ai-gateway-basic", "reconcileID": "100f9975-0a7d-493c-a454-686fad557b06", "error": "failed to create backend auth: failed to get secret envoy-ai-gateway-basic-hunyuan-credentials: secret envoy-ai-gateway-basic-hunyuan-credentials does not contain key credentials"}
```
