### ISSUE TITLE
Consider using PolicyAttachment or Filter extension instead of an abstracted Route and Backend

### ISSUE THREAD

**Issue by arkodg** [theagentrouter/agent-router#764]
*Description*:
>Describe the issue.

One  issue with abstracting resources to `AIGatewayRoute` and `AIServiceBackend` is that users need to specify the xRoute name in the targetRef of the EG policies, documentation to outline name mapping/translation is helpful, but lack of this information at deploy time, may make troubleshooting hard as well as confidence in deploy due to an uncreated targetRef.

a Policy extension or a filter extension (at the route rule or backend level) may have better UX.

[optional *Relevant Links*:]
>Any extra documentation required to understand the issue.

**Comment by Xunzhuo** [comment]
Hey @arkodg, can you elaborate more? I dont get in clearly.  You mean if we create the Policy and targetRef is AIGatewayRoute/AIServiceBackend will be not working?

Like example: https://aigateway.envoyproxy.io/docs/latest/capabilities/fallback#configuring-fallback-behavior

We create the btp and targetRef is the httpRoute instead of the aigwroute, this is a bit confused to people, right?

**Comment by arkodg** [comment]
hey @Xunzhuo referring to replacing `AIGatewayRoute` and `AIServiceBackend` completely with Gateway API extensions instead

using the 3 extension points
* Policy
* Filter
* BackendRef

to define an external resource that can be translated by the Extension Server https://gateway.envoyproxy.io/docs/tasks/extensibility/extension-server/

example

```
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIProviderPolicy
metadata:
  name: openai-policy
spec:
  targetRefs:
  - kind: HTTPRoute
    name: eg
    group: gateway.networking.k8s.io
  schema:
    name: OpenAI
```
