### ISSUE TITLE
Streaming requests never processing body [500 internal server error]

### ISSUE THREAD

**Issue by ion-elgreco** [theagentrouter/agent-router#805]
*Description*:
When I try to send a very large request with requests set to streaming in the EnvoyExtensionPolicy, it will throw 500 internal server errors, see below:

```
time=2025-06-30T10:01:12.740Z level=DEBUG msg="handling a new stream" config_uuid=ai-gateway-provision
time=2025-06-30T10:01:12.742Z level=DEBUG msg="request headers processing" request_id=d489cf5d-a2cd-4730-8f04-a924a4b8cb4c is_upstream_filter=false request_headers.:authority=[REDACTED] request_headers.:path=/v1/chat/completions request_headers.:method=POST request_headers.:scheme=https request_headers.content-type=application/json request_headers.authorization=[REDACTED] request_headers.accept=*/* request_headers.user-agent="Zed/0.192.7 (macos; aarch64)" request_headers.content-length=1014506 request_headers.x-forwarded-for=[redacted] request_headers.x-forwarded-proto=https request_headers.x-envoy-external-address=[redacted] request_headers.x-request-id=d489cf5d-a2cd-4730-8f04-a924a4b8cb4c
time=2025-06-30T10:01:12.742Z level=DEBUG msg="request headers processed" request_id=d489cf5d-a2cd-4730-8f04-a924a4b8cb4c is_upstream_filter=false response=request_headers:{}
```
Normally it should mention after this line it started processing the body but it doesn't in this case and the Envoy container mentions the request failed with 500 internal server error.

*Repro steps*:
Not sure how reproducible is but, try to make a huge streaming request with Zed, for example the whole Envoy AI gateway selected as files and set the EnvoyExtensionPolicy for requests to `Streamed`.

>**Note**: If there are privacy concerns, sanitize the data prior to
sharing.

*Environment*:
>Include the environment like gateway version, envoy version and so on.
aigw: 0.2.1
envoy: 1.4.1

*Logs*:
>Include the access logs and the Envoy logs.

**Comment by mathetake** [comment]
could you check if this happens after #828 ?

**Comment by ion-elgreco** [comment]
@mathetake sure, give me a sec :)

**Comment by ion-elgreco** [comment]
@mathetake yes it still throws 500 internal server error directly, when you set it to streamed. Even with ClientTrafficPolicy

**Comment by mathetake** [comment]
could you provide gateway logs, configurations as well as how gateway pods are configured?

**Comment by ion-elgreco** [comment]
gateway-extproc container:
```
time=2025-07-07T18:00:11.303Z level=INFO msg="Starting health check HTTP server" addr=:1065
time=2025-07-07T18:00:44.815Z level=DEBUG msg="handling a new stream" config_uuid=ai-gateway-provision-ai-gateway-provisioner
time=2025-07-07T18:00:44.815Z level=DEBUG msg="request headers processing" request_id=994eb977-8e6f-41bb-8845-1aae32376c37 is_upstream_filter=false request_headers.:authority=[redacted] request_headers.:path=/v1/chat/completions request_headers.:method=POST request_headers.:scheme=https request_headers.content-type=application/json request_headers.authorization=[REDACTED] request_headers.accept=*/* request_headers.user-agent="Zed/0.193.3 (macos; aarch64)" request_headers.content-length=686928 request_headers.x-forwarded-for=[redacted] request_headers.x-forwarded-proto=https request_headers.x-envoy-external-address=[redacted] request_headers.x-request-id=994eb977-8e6f-41bb-8845-1aae32376c37
time=2025-07-07T18:00:44.815Z level=DEBUG msg="request headers processed" request_id=994eb977-8e6f-41bb-8845-1aae32376c37 is_upstream_filter=false response=request_headers:{}
```

envoy container:
```
{":authority":"[REDACTED]","bytes_received":32554,"bytes_sent":0,"connection_termination_details":null,"downstream_local_address":"[redacted]","downstream_remote_address":"[redacted]","duration":2,"method":"POST","protocol":"HTTP/1.1","requested_server_name":"[redacted]","response_code":500,"response_code_details":"direct_response","response_flags":"-","route_name":"httproute/default/ai-gateway-provision-ai-gateway-provisioner/rule/8/match/0/[redacted]","start_time":"2025-07-07T18:00:44.814Z","upstream_cluster":null,"upstream_host":null,"upstream_local_address":null,"upstream_transport_failure_reason":null,"user-agent":"Zed/0.193.3 (macos; aarch64)","x-envoy-origin-path":"/v1/chat/completions","x-envoy-upstream-service-time":null,"x-forwarded-for":"[redacted]","x-request-id":"994eb977-8e6f-41bb-8845-1aae32376c37"}
```

The AIGW and EG is quite standard, only thing I add is ClientTrafficPolicy (which is hardcoded to 150Mi now, as you can see in the provisioner helm chart) and API key auth on top.

**Comment by mathetake** [comment]
sorry these logs aren't helpful to debug further unfortunately. could you provide more details like the envoy logs with this config (you can check how to use it in [the example here](https://github.com/envoyproxy/ai-gateway/blob/9aa4192229aaaa94852fd1dc0ce6ed8a9cb224ff/cmd/aigw/ai-gateway-default-resources.yaml#L48-L62).) This will help emit more info especially on who creates the 500 response.

```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-ai-gateway
  namespace: default
spec:
  logging:
    level:
      default: error
```

as well as the concrete example configuration. otherwise it's not likely that i could reproduce or investigate further.

**Comment by ion-elgreco** [comment]
> sorry these logs aren't helpful to debug further unfortunately. could you provide more details like the envoy logs with this config (you can check how to use it in [the example here](https://github.com/envoyproxy/ai-gateway/blob/9aa4192229aaaa94852fd1dc0ce6ed8a9cb224ff/cmd/aigw/ai-gateway-default-resources.yaml#L48-L62).) This will help emit more info especially on who creates the 500 response.
> 
> ```
> apiVersion: gateway.envoyproxy.io/v1alpha1
> kind: EnvoyProxy
> metadata:
>   name: envoy-ai-gateway
>   namespace: default
> spec:
>   logging:
>     level:
>       default: error
> ```
> 
> as well as the concrete example configuration. otherwise it's not likely that i could reproduce or investigate further.

Setting it to Error emits no additional logging, here is the full CRDs that are templated:

```yaml
---
# Source: ai-gateway-provisioner/templates/aigatewayroute.yaml
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIGatewayRoute
metadata:
  name: ai-gateway-provision-ai-gateway-provisioner
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  schema:
    name: OpenAI
  targetRefs:
    - name: ai-gateway-provision-ai-gateway-provisioner
      kind: Gateway
      group: gateway.networking.k8s.io
  rules:
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: o1
      backendRefs:
        - name: envoy-ai-gateway-azure
      timeouts:
        request: 90s
        backendRequest: 90s
    - matches:
        - headers:
            - type: Exact
              name: x-ai-eg-model
              value: gpt-4.1
      backendRefs:
        - name: envoy-ai-gateway-azure
      timeouts:
        request: 120s
        backendRequest: 120s
---
# Source: ai-gateway-provisioner/templates/aiservicebackend.yaml
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: envoy-ai-gateway-azure
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  schema:
    name: AzureOpenAI
    version: 2024-12-01-preview
  backendRef:
    name: envoy-ai-gateway-azure
    kind: Backend
    group: gateway.envoyproxy.io
  backendSecurityPolicyRef:
    name: azure-openai-key
    kind: BackendSecurityPolicy
    group: aigateway.envoyproxy.io
---
# Source: ai-gateway-provisioner/templates/backend.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: envoy-ai-gateway-azure
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
    - fqdn:
        hostname: [redacted]
        port: 443
---
# Source: ai-gateway-provisioner/templates/backendsecuritypolicy.yaml
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: azure-openai-key
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  type: APIKey
  apiKey:
    secretRef:
      name: azure-openai-key
      namespace: default
---
# Source: ai-gateway-provisioner/templates/backendtlspolicy.yaml
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: envoy-ai-gateway-basic-openai-tls
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  targetRefs:
    - group: gateway.envoyproxy.io
      kind: Backend
      name: envoy-ai-gateway-azure
  validation:
    wellKnownCACertificates: "System"
    hostname: [redacted]
---
# Source: ai-gateway-provisioner/templates/clienttrafficpolicy.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: 'ai-gateway-provision-ai-gateway-provisioner-limit'
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ai-gateway-provision-ai-gateway-provisioner
  connection:
    bufferLimit: 150Mi
---
# Source: ai-gateway-provisioner/templates/envoyproxy.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: ai-gateway-provision-ai-gateway-provisioner
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyService:
        type: LoadBalancer  # or NodePort, LoadBalanc
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      envoyDeployment:
        container:
          image: [redacted]/envoyproxy/envoy:distroless-v1.34.1
---
# Source: ai-gateway-provisioner/templates/gateway.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ai-gateway-provision-ai-gateway-provisioner
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: cluster-ca-issuer
    cert-manager.io/duration: 8760h
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  gatewayClassName: envoy-ai-gateway
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: ai-gateway-provision-ai-gateway-provisioner
  listeners:
  - hostname: [redacted]
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - name: aigw-envoy-tls
      mode: Terminate
---
# Source: ai-gateway-provisioner/templates/gatewayclass.yaml
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: envoy-ai-gateway
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
# Source: ai-gateway-provisioner/templates/securitypolicy.yaml
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: "ai-gateway-provision-ai-gateway-provisioner-security"
  namespace: default
  labels:
    helm.sh/chart: ai-gateway-provisioner-0.1.0
    app.kubernetes.io/name: ai-gateway-provision-ai-gateway-provisioner
    app.kubernetes.io/instance: ai-gateway-provision
    app.kubernetes.io/managed-by: Helm
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ai-gateway-provision-ai-gateway-provisioner
  apiKeyAuth:
    credentialRefs:
    - group: ""
      kind: Secret
      name: "envoy-api-key"
    extractFrom:
    - headers:
      - "Authorization"
```
